### ISSUE TITLE
Bitcoin Accepted Here: Merchant Design Workshop #0

### ISSUE THREAD

**Issue by johnsBeharry** [BitcoinDesign/Meta#38]
```meta
Date: 2020-10-27
Time: 9:15am
Timezone: PT (US)
Duration: 1h
UTCTime: 2020-10-27T09:15:00.000-07:00
```

![amazing cover image](https://user-images.githubusercontent.com/183140/97210784-21f05600-17cf-11eb-864c-d0185b9c03e4.gif)

The goal with these design sprints is to address challenges facing merchants after they have setup their stores to accept bitcoin. 

We will brainstorm, prototype and test potential solutions.

Please prep for the workshop beforehand by reading this primer on [bitcoin merchant invoices](https://github.com/peakshift/bitcoin-ux/blob/master/merchants/invoices.md).

### Agenda

1. ~~Definition~~
2. ~~Feature Mapping~~
3. ~~Alignment Personas~~
4. ~~Problem Statements~~
5. ~~Expert Interview~~
6. ~~Affinity Mapping~~
7. Project Intro
8. Review Research
9. HMW (Group Activity)
10. Affinity Mapping (Group Activity)
11. Journey Mapping (Group Activity)

### Check your timezone

- https://everytimezone.com/s/2a3b0917

### Join the call

- https://meet.jit.si/bitcoindesign

### Calendar invite

- https://raw.githubusercontent.com/BitcoinDesign/Meta/calendar/events.ical

**Comment by pavlenex** [comment]
Thanks everyone for participating in the Workshop 0. 
The sprint lasted for ~4 hours and we came up with some really good ideas.

Instead of posting a regular notes from the sprint, we tried to visualize it in a video, so that anybody interested can quickly sync in on what we've been up to and better prepare for the next meeting.

The video is here https://youtu.be/OGrzjl8A5vg
Miro board here https://miro.com/app/board/o9J_kh9LoWM=/

Please let me know if you find this sort of videos helpful or you prefer notes.
