### ISSUE TITLE
Community call format

### ISSUE THREAD

**Issue by GBKS** [BitcoinDesign/Meta#5]
As we organize more open calls for the community, it might be helpful to consider different aspects of the format so the calls can be as useful and interesting as possible for everyone. I'd like to kick this off with some thoughts.

**General suggestions**

- Calls should not be used to make decisions as that would exclude too many people, and group dynamics might affect the result
- Real or fake names are fine
- Lurking is fine although participation is encouraged

**Should we record calls?**

- Pro: calls can be watched later by people who just didn't have time
- Pro: more transparency (if calls are not used for big decisions, transparency may not be a big issue)
- Con: people might be more comfortable asking questions and being open about their experiences when they know a call is not recorded
- Con: people might not join when they fear their privacy might get compromised

**Should we transcribe calls?**

- Pro: short, concise summaries may mean more people, who couldn't attend, read them and are in the know
- Con: somebody needs to create them

**How often should calls be?**

- There were 3 weeks between calls 0 and 1, calls were 1 hour each 
- Should we do shorter calls more often? 30 minutes every two weeks? Or longer calls less often?
- @johnsBeharry started open sessions, do we want to "formalize" this format somehow or keep it spontaneous?

**What week day should calls be?**

- Calls 0 and 1 were on Wednesdays
- Should we alternate between 2-3 week days to allow for diverse participation?

**What time of day should calls be?**

- Calls 0 and 1 were at 9am PT
- Should we alternate between 2-3 time slots to allow for diverse participation? We have people from 18 time zones in Slack. Allowing as many people as possible to participate is a big goal for me, and I think time of day is a big factor in that

**What format should calls have?**

- Update on what happened since the last call
- Important community topics
- Show and tell
- Design/project review
- Coffee chat (open discussion)
- Allow anyone to suggest topics for discussion
- Focus on specific guide content topics (one call about privacy, next about key management, etc)
- Should we alternate formats or decide based on suggested topics?

**How should we announce calls?**

- Is a Slack channel ping enough? Should we announce on Twitter also? Anywhere else?
- Do we need to create Calendar invites?

**What tools do we use?**

- Calls 0 and 1 were on Google Meet
- [Jitsi](https://jitsi.org) has been discussed but is known to be flaky for larger groups

That's what I have for now. Please chime in so we can make the calls as cool as a fool in a swimming pool.

**Comment by ecurrencyhodler** [comment]
### Should we record calls?
I think it'd be great if we could record calls so that all those who can't make the meeting (whether due to work/illness/timezone) can at least stay in sync with the rest of the community. The entire call does not have to be recorded. We should also clarify at the beginning of every meeting which portions will be recorded so those who wish to preserve their privacy can.

### What should be recorded?
Here are some examples of topics that could be recorded:
- Presentations
- Announcements
- Progress reports on the Bitcoin Design Guide

### What shouldn't be recorded?
- Discussions to encourage community discussion. This will encourage people to speak freely and not exclude those who wish to preserve their privacy.

I've also pre-emptively reserved a YT channel where we can host the calls we could use if needed: https://www.youtube.com/channel/UC77befXcaLOyVX8IO9c8CoA

**Comment by johnsBeharry** [comment]
Just wanted to highlight that we also seeing other projects which are actively engaged in the community also adapting this call format for their own as with Bitcoin Design GUI Call (#12). I think this is really great to see such working groups come together to tackle specific topics.

I've just added a label for "call" to make them easier to identify in the [issues tab](https://github.com/BitcoinDesign/Meta/issues?q=is%3Aissue+is%3Aopen+label%3Acall).

**Comment by danielnordh** [comment]
Suggest we close this issue by creating community-calls.md to summarize the parts we have now de-facto adopted over the last 6 months. Further discussion can happen around that file.
